import React, { useState, useEffect, useRef, useCallback } from 'react'
import Webcam from 'react-webcam'
import { Mic, MicOff, Video, VideoOff, PhoneOff, Send, UserCircle2, Settings } from 'lucide-react'

// --- Import your custom hooks ---
import { useSocket } from '@/contexts/SocketContext'
import { useAuth } from '@/contexts/AuthContext'
import { Popover, PopoverContent, PopoverTrigger } from '../ui/popover'
import { Label } from '../ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select'

// --- CONFIGURATION FOR WEBRTC ---
// Public STUN servers are used to help clients discover their public IP addresses.
const iceServers = {
  iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:stun1.l.google.com:19302' }]
}

// --- CSS FOR THE TYPING INDICATOR ANIMATION ---
const styles = `
.typing-indicator span {
    height: 8px;
    width: 8px;
    background-color: #9E9EA1;
    border-radius: 50%;
    display: inline-block;
    animation: bounce 1.4s infinite ease-in-out both;
}
.typing-indicator span:nth-of-type(2) {
    animation-delay: -0.32s;
}
.typing-indicator span:nth-of-type(3) {
    animation-delay: -0.16s;
}
@keyframes bounce {
    0%, 80%, 100% { transform: scale(0); }
    40% { transform: scale(1.0); }
}
`

// Define a type for our chat messages
interface ChatMessage {
  id: string
  sender_id: string
  content: string
  created_at?: string
}

// Define the props for our component
interface VideoChatRoomProps {
  chat_room_id: string
  onLeave: () => void
}

const VideoChatRoom: React.FC<VideoChatRoomProps> = ({ chat_room_id, onLeave }) => {
  const socket = useSocket()
  const { user } = useAuth()

  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [newMessage, setNewMessage] = useState('')
  const [isMuted, setIsMuted] = useState(false)
  const [isCameraOff, setIsCameraOff] = useState(false)

  const [mics, setMics] = useState<MediaDeviceInfo[]>([])
  const [cams, setCams] = useState<MediaDeviceInfo[]>([])
  const [selectedMicId, setSelectedMicId] = useState<string>('')
  const [selectedCamId, setSelectedCamId] = useState<string>('')

  // const [isLocalStreamReady, setIsLocalStreamReady] = useState(false)

  const [typingUsers, setTypingUsers] = useState<string[]>([])
  const typingTimeoutRef = useRef<NodeJS.Timeout | null>(null)

  const localVideoRef = useRef<Webcam>(null)
  const remoteVideoRef = useRef<HTMLVideoElement>(null)
  const chatContainerRef = useRef<HTMLDivElement>(null)

  // --- Refs specifically for WebRTC ---
  const peerConnectionRef = useRef<RTCPeerConnection | null>(null)
  const otherUserSocketIdRef = useRef<string | null>(null)

  // ====================================================================
  // --- START OF WEBRTC LOGIC ---
  // These functions will replace the console.log placeholders.
  // ====================================================================

  const hasJoinedCallRoomRef = useRef(false)

  const getDevices = useCallback(async () => {
    try {
      const devices = await navigator.mediaDevices.enumerateDevices()
      const audioInputDevices = devices.filter((device) => device.kind === 'audioinput')
      const videoInputDevices = devices.filter((device) => device.kind === 'videoinput')

      setMics(audioInputDevices)
      setCams(videoInputDevices)

      // Set default devices if not already set
      if (audioInputDevices.length > 0 && !selectedMicId) {
        setSelectedMicId(audioInputDevices[0].deviceId)
      }
      if (videoInputDevices.length > 0 && !selectedCamId) {
        setSelectedCamId(videoInputDevices[0].deviceId)
      }
    } catch (err) {
      console.error('Error enumerating devices:', err)
    }
  }, [selectedMicId, selectedCamId])

  const createPeerConnection = useCallback(() => {
    // Clean up any existing connection before creating a new one.
    if (peerConnectionRef.current) {
      peerConnectionRef.current.close()
    }

    const pc = new RTCPeerConnection(iceServers)

    // This event fires when a new ICE candidate is generated by the local machine.
    pc.onicecandidate = (event) => {
      if (event.candidate && otherUserSocketIdRef.current) {
        console.log('Sending ICE candidate to peer:', otherUserSocketIdRef.current)
        socket.emit('call:ice-candidate', {
          candidate: event.candidate,
          to: otherUserSocketIdRef.current
        })
      }
    }

    // This event fires when the remote peer adds a track (their video/audio stream).
    pc.ontrack = (event) => {
      console.log('Received remote track from peer.')
      if (remoteVideoRef.current && event.streams[0]) {
        // Attach the remote stream to the remote video element.
        remoteVideoRef.current.srcObject = event.streams[0]
      }
    }

    // Add local media tracks (from your webcam) to the connection to be sent.
    const localStream = localVideoRef.current?.stream
    if (localStream) {
      console.log('Adding local tracks to the peer connection.')
      localStream.getTracks().forEach((track) => {
        pc.addTrack(track, localStream)
      })
    }

    peerConnectionRef.current = pc
    return pc
  }, [socket])

  // CALLED WHEN THE SERVER SAYS A NEW USER JOINED (I am the first one here)
  const handleUserJoined = useCallback(
    async ({ peerId }: { peerId: string }) => {
      console.log(`A new user (${peerId}) joined. I will initiate the call.`)
      otherUserSocketIdRef.current = peerId

      const pc = createPeerConnection()
      const offer = await pc.createOffer()
      await pc.setLocalDescription(offer)

      console.log('Sending offer to new user:', peerId)
      socket.emit('call:offer', { offer, to: peerId })
    },
    [socket, createPeerConnection]
  )

  // CALLED WHEN I RECEIVE AN OFFER (I am the second one to join)
  const handleOffer = useCallback(
    async ({ offer, from }: { offer: RTCSessionDescriptionInit; from: string }) => {
      console.log(`Received offer from user ${from}.`)
      otherUserSocketIdRef.current = from

      const pc = createPeerConnection()
      await pc.setRemoteDescription(new RTCSessionDescription(offer))

      const answer = await pc.createAnswer()
      await pc.setLocalDescription(answer)

      console.log('Sending answer back to user:', from)
      socket.emit('call:answer', { answer, to: from })
    },
    [socket, createPeerConnection]
  )

  // CALLED WHEN I RECEIVE AN ANSWER (I was the first one, now getting a reply)
  const handleAnswer = useCallback(async ({ answer }: { answer: RTCSessionDescriptionInit }) => {
    console.log('Received answer from peer.')
    // Check if a connection exists and is in the correct state to receive an answer.
    if (peerConnectionRef.current?.signalingState === 'have-local-offer') {
      await peerConnectionRef.current.setRemoteDescription(new RTCSessionDescription(answer))
    }
  }, [])

  // CALLED WHEN I RECEIVE A NETWORK CANDIDATE
  const handleNewICECandidate = useCallback(async ({ candidate }: { candidate: RTCIceCandidateInit }) => {
    if (peerConnectionRef.current) {
      console.log('Received new ICE candidate from peer.')
      try {
        await peerConnectionRef.current.addIceCandidate(new RTCIceCandidate(candidate))
      } catch (e) {
        console.error('Error adding received ICE candidate', e)
      }
    }
  }, [])

  const handleUserLeft = useCallback(({ peerId }: { peerId: string }) => {
    console.log(`User ${peerId} has left the call.`)
    if (otherUserSocketIdRef.current === peerId) {
      if (peerConnectionRef.current) {
        peerConnectionRef.current.close()
        peerConnectionRef.current = null
      }
      otherUserSocketIdRef.current = null
      if (remoteVideoRef.current) {
        remoteVideoRef.current.srcObject = null // Clear the remote video
      }
    }
  }, [])

  // ====================================================================
  // --- END OF WEBRTC LOGIC ---
  // ====================================================================

  // Effect to automatically scroll the chat window
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight
    }
  }, [messages])

  useEffect(() => {
    if (localVideoRef.current?.stream) {
      const audioTracks = (localVideoRef.current.stream as MediaStream).getAudioTracks()
      if (audioTracks.length > 0) audioTracks[0].enabled = !isMuted
    }
  }, [isMuted])

  // Effect to handle turning the camera on/off
  useEffect(() => {
    if (localVideoRef.current?.stream) {
      const videoTracks = (localVideoRef.current.stream as MediaStream).getVideoTracks()
      if (videoTracks.length > 0) videoTracks[0].enabled = !isCameraOff
    }
  }, [isCameraOff])

  useEffect(() => {
    const replaceVideoTrack = async () => {
      if (peerConnectionRef.current && localVideoRef.current?.stream) {
        const videoTrack = (localVideoRef.current.stream as MediaStream).getVideoTracks()[0]
        const sender = peerConnectionRef.current.getSenders().find((s) => s.track?.kind === 'video')
        if (sender && videoTrack) {
          await sender.replaceTrack(videoTrack)
        }
      }
    }
    replaceVideoTrack()
  }, [selectedCamId])

  useEffect(() => {
    const replaceAudioTrack = async () => {
      if (peerConnectionRef.current && localVideoRef.current?.stream) {
        const audioTrack = (localVideoRef.current.stream as MediaStream).getAudioTracks()[0]
        const sender = peerConnectionRef.current.getSenders().find((s) => s.track?.kind === 'audio')
        if (sender && audioTrack) {
          await sender.replaceTrack(audioTrack)
        }
      }
    }
    replaceAudioTrack()
  }, [selectedMicId])

  // Main effect for handling all socket event listeners
  useEffect(() => {
    if (!socket || !user) return

    socket.emit('chat:joinRoom', chat_room_id)

    const handleChatMessage = (message: ChatMessage) => {
      setTypingUsers((prev) => prev.filter((id) => id !== message.sender_id))
      setMessages((prevMessages) => [...prevMessages, message])
    }

    const handleTyping = ({ sender_id, is_typing }: { sender_id: string; is_typing: boolean }) => {
      setTypingUsers((prev) => (is_typing ? [...prev, sender_id] : prev.filter((id) => id !== sender_id)))
    }

    // --- Register ALL Listeners ---
    socket.on('chat:message', handleChatMessage)
    socket.on('chat:typing', handleTyping)
    socket.on('user:joined', handleUserJoined)
    socket.on('call:offer', handleOffer)
    socket.on('call:answer', handleAnswer)
    socket.on('call:ice-candidate', handleNewICECandidate)
    socket.on('user:left', handleUserLeft)

    // --- Cleanup on component unmount ---
    return () => {
      socket.off('chat:message', handleChatMessage)
      socket.off('chat:typing', handleTyping)
      socket.off('user:joined', handleUserJoined)
      socket.off('call:offer', handleOffer)
      socket.off('call:answer', handleAnswer)
      socket.off('call:ice-candidate', handleNewICECandidate)
      socket.off('user:left', handleUserLeft)

      socket.emit('chat:leaveRoom', chat_room_id)
      socket.emit('call:leaveRoom', chat_room_id)
      if (peerConnectionRef.current) {
        peerConnectionRef.current.close()
        peerConnectionRef.current = null
      }
      otherUserSocketIdRef.current = null
    }
  }, [socket, user, chat_room_id, handleUserJoined, handleOffer, handleAnswer, handleNewICECandidate, handleUserLeft])

  const handleUserMedia = () => {
    getDevices()

    if (socket && !hasJoinedCallRoomRef.current) {
      console.log('Local camera is ready. Joining call room now.')
      socket.emit('call:joinRoom', chat_room_id)
      hasJoinedCallRoomRef.current = true
    }
  }

  // Chat and Typing handlers remain unchanged
  const handleSendMessage = useCallback(() => {
    if (typingTimeoutRef.current) {
      clearTimeout(typingTimeoutRef.current)
    }
    if (socket && user) {
      socket.emit('chat:typing', { room_id: chat_room_id, sender_id: user.user_id, is_typing: false })
    }
    if (newMessage.trim() && socket && user) {
      const messageData = { room_id: chat_room_id, sender_id: user.user_id, message: newMessage }
      socket.emit('chat:message', messageData)
      setMessages((prev) => [...prev, { id: `temp_${Date.now()}`, sender_id: user.user_id, content: newMessage }])
      setNewMessage('')
    }
  }, [newMessage, socket, user, chat_room_id])

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewMessage(e.target.value)
    if (!socket || !user) return
    if (typingTimeoutRef.current) {
      clearTimeout(typingTimeoutRef.current)
    }
    socket.emit('chat:typing', { room_id: chat_room_id, sender_id: user.user_id, is_typing: true })
    typingTimeoutRef.current = setTimeout(() => {
      socket.emit('chat:typing', { room_id: chat_room_id, sender_id: user.user_id, is_typing: false })
    }, 2000)
  }

  return (
    <>
      <style>{styles}</style>
      <div className='flex h-screen flex-col bg-gray-900 font-sans text-white'>
        <div className='flex flex-1 overflow-hidden'>
          {/* Main Content Area: Video Streams */}
          <div className='relative flex flex-1 flex-col gap-4 p-4'>
            <div className='relative flex-1 overflow-hidden rounded-lg border border-gray-700 bg-black'>
              <video ref={remoteVideoRef} autoPlay playsInline className='h-full w-full object-cover' />
              <div className='bg-opacity-50 absolute bottom-2 left-2 rounded bg-black px-2 py-1 text-sm font-semibold'>
                Remote User
              </div>
            </div>
            <div className='absolute top-4 right-4 z-10 h-auto w-48 self-end overflow-hidden rounded-lg border-2 border-gray-500 bg-black shadow-lg lg:w-64'>
              <div className={`transition-opacity duration-300 ${isCameraOff ? 'opacity-100' : 'opacity-0'}`}>
                <div
                  className='flex h-full w-full items-center justify-center bg-gray-800'
                  style={{ aspectRatio: '16/9' }}
                >
                  <UserCircle2 className='h-16 w-16 text-gray-500' />
                </div>
              </div>
              <div
                className={`absolute top-0 left-0 h-full w-full transition-opacity duration-300 ${isCameraOff ? 'opacity-0' : 'opacity-100'}`}
              >
                <Webcam
                  audio={true}
                  ref={localVideoRef}
                  mirrored={false}
                  className='h-full w-full object-cover'
                  onUserMedia={handleUserMedia}
                  onUserMediaError={(err) => console.error('Webcam Error:', err)}
                  audioConstraints={{ deviceId: selectedMicId ? { exact: selectedMicId } : undefined }}
                  videoConstraints={{
                    deviceId: selectedCamId ? { exact: selectedCamId } : undefined,
                    width: 1280,
                    height: 720
                  }}
                />
              </div>
              <div className='bg-opacity-50 absolute bottom-1 left-1 rounded bg-black px-2 py-0.5 text-xs font-semibold'>
                You
              </div>
            </div>
          </div>

          {/* Side Panel: Chat */}
          <div className='flex w-80 flex-col border-l border-gray-700 bg-gray-800'>
            <div className='border-b border-gray-700 p-4'>
              <h2 className='text-lg font-bold'>Live Chat</h2>
              <p className='truncate text-xs text-gray-400'>Room: {chat_room_id}</p>
            </div>
            <div ref={chatContainerRef} className='flex-1 space-y-4 overflow-y-auto p-4'>
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  className={`flex flex-col ${msg.sender_id === user?.user_id ? 'items-end' : 'items-start'}`}
                >
                  <div
                    className={`max-w-xs rounded-lg px-3 py-2 text-sm shadow ${msg.sender_id === user?.user_id ? 'rounded-br-none bg-blue-600' : 'rounded-bl-none bg-gray-600'}`}
                  >
                    {msg.content}
                  </div>
                </div>
              ))}
            </div>
            <div className='flex h-6 items-center px-4'>
              {typingUsers.filter((id) => id !== user?.user_id).length > 0 && (
                <div className='flex items-center gap-2 text-sm text-gray-400'>
                  <div className='typing-indicator'>
                    <span></span>
                    <span></span>
                    <span></span>
                  </div>
                </div>
              )}
            </div>
            <div className='border-t border-gray-700 p-4'>
              <div className='flex gap-2'>
                <input
                  type='text'
                  value={newMessage}
                  onChange={handleInputChange}
                  onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                  placeholder='Type a message...'
                  className='flex-1 rounded-full bg-gray-700 px-4 py-2 text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none'
                />
                <button
                  onClick={handleSendMessage}
                  className='flex-shrink-0 rounded-full bg-blue-600 p-2 transition-colors hover:bg-blue-500'
                >
                  <Send size={20} />
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Control Bar */}
        <div className='bg-opacity-50 flex items-center justify-center gap-6 border-t border-gray-700 bg-gray-900 py-3'>
          <button
            onClick={() => setIsMuted(!isMuted)}
            className={`rounded-full p-3 transition-colors ${isMuted ? 'bg-red-500 text-white' : 'bg-gray-600 hover:bg-gray-500'}`}
          >
            {isMuted ? <MicOff size={24} /> : <Mic size={24} />}
          </button>
          <button
            onClick={() => setIsCameraOff(!isCameraOff)}
            className={`rounded-full p-3 transition-colors ${isCameraOff ? 'bg-red-500 text-white' : 'bg-gray-600 hover:bg-gray-500'}`}
          >
            {isCameraOff ? <VideoOff size={24} /> : <Video size={24} />}
          </button>

          <Popover>
            <PopoverTrigger asChild>
              <button className='cursor-pointer rounded-full bg-gray-600 p-3 transition-colors hover:bg-gray-500'>
                <Settings size={24} />
              </button>
            </PopoverTrigger>
            <PopoverContent className='w-auto border-gray-600 bg-gray-800 text-white'>
              <div className='grid gap-4'>
                <div className='space-y-2'>
                  <h4 className='leading-none font-medium'>Settings</h4>
                  <p className='text-sm text-gray-400'>Configure your audio and video devices.</p>
                </div>
                <div className='grid gap-2'>
                  <div className='grid grid-cols-2 items-center gap-4'>
                    <Label htmlFor='camera-select' className='text-right'>
                      Camera
                    </Label>
                    <Select value={selectedCamId} onValueChange={setSelectedCamId}>
                      <SelectTrigger
                        id='camera-select'
                        className='col-span-2 cursor-pointer border-gray-500 bg-gray-700'
                      >
                        <SelectValue placeholder='Select Camera' />
                      </SelectTrigger>
                      <SelectContent className='border-gray-600 bg-gray-800 text-white'>
                        {cams.map((cam) => (
                          <SelectItem
                            key={cam.deviceId}
                            value={cam.deviceId}
                            className='cursor-pointer hover:bg-gray-700! hover:text-white!'
                          >
                            {cam.label || `Camera ${cams.indexOf(cam) + 1}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className='grid grid-cols-2 items-center gap-4'>
                    <Label htmlFor='mic-select' className='text-right'>
                      Microphone
                    </Label>
                    <Select value={selectedMicId} onValueChange={setSelectedMicId}>
                      <SelectTrigger id='mic-select' className='col-span-2 cursor-pointer border-gray-500 bg-gray-700'>
                        <SelectValue placeholder='Select Microphone' />
                      </SelectTrigger>
                      <SelectContent className='border-gray-600 bg-gray-800 text-white'>
                        {mics.map((mic) => (
                          <SelectItem
                            key={mic.deviceId}
                            value={mic.deviceId}
                            className='cursor-pointer hover:bg-gray-700! hover:text-white!'
                          >
                            {mic.label || `Microphone ${mics.indexOf(mic) + 1}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
            </PopoverContent>
          </Popover>

          <button onClick={onLeave} className='rounded-full bg-red-600 p-3 transition-colors hover:bg-red-700'>
            <PhoneOff size={24} />
          </button>
        </div>
      </div>
    </>
  )
}

export default VideoChatRoom
